### ISSUE TITLE
test ecolumn.py

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/rscooler#1]
Run Warp with ecolumn.py and, if necessary, modify rsbeam and rswarp repositories to enable necessary postprocessing, plots, etc.

**Comment by bruhwiler** [comment]
The file runs with no problem in the 'beamsim' container.
It takes about 3 seconds per time step inside Virtual Box on my PC.
Various particle and field data is written to plain text files, labeled with dump number.

**Comment by cchall** [comment]
I moved it onto an IPython notebook on the blade and ran it without any
real problem.
I did have to add the full path to load the additional modules it imports
from Warp.

I'm looking at what needs to be done as far as post-processing next.
